/* eslint-disable prettier/prettier */
export enum StatusType {
  CREATEDRAFTED = 'CREATEDRAFTED',
  CREATEAPPROVED = 'CREATEAPPROVED',
  UPDATEDRAFTED = 'UPDATEDRAFTED',
  UPDATEAPPROVED = 'UPDATEAPPROVED',
  DELETEDRAFTED = 'DELETEDRAFTED',
  DELETEAPPROVED = 'DELETEAPPROVED',
  REVIEWED = 'REVIEWED',
  DELETED = 'DELETED',
}
